- Classes/Eel/FormHelper.php
- README.md
- Resources/Private/Fusion/Prototypes/FieldComponent.fusion
- Resources/Private/Fusion/Prototypes/FieldContainer.fusion
Instead of using `name` and `property` as synonym options with slightly different syntax the `property` is removed and only the `name` option is left to define the fieldname in html-sytax with square  brackets for nested properties.
This straightens the interface of the form helper an allows to stop exposing fieldNameToPath to eel.
> TASK: Remove `property` from field in favor of consistent use of `name`

- README.md
- Resources/Private/Fusion/Prototypes/FieldComponent.fusion
- Resources/Private/Fusion/Prototypes/Form.fusion
- Resources/Private/Fusion/Prototypes/Neos/BackendModule.FieldContainer.fusion
In addition the handling of form and field context was adjusted for simplicity.
Also the `Neos.Fusion.Form:Neos.BackendModule.FieldContainer` is adjusted
to inherit from `Neos.Fusion.Form:FieldComponent`.
> DOCS: Add documentation for extending Neos.Fusion.Form

- Classes/Eel/FormHelper.php
> BUGFIX: Create empty `field` with correct arguments when no name is given

- README.md
- Resources/Private/Fusion/Prototypes/Textarea.fusion
Without this change malicious content submitted for a textarea field will be
rerendered without checks again and can insert code to the website.
The other fieldtypes are not affected as those render the values as attributes which get htmlspecialchars applied automatically.
> SECURITY: Pass content for textarea field trough htmlspecialchars

- composer.json
See https://github.com/neos/neos-development-collection/issues/3227
> TASK: Allow newer PHPUnit versions (7.1.x, 8.x, 9.x)

- .github/workflows/build.yml
- .travis.yml
Travis was disabled a while ago, this restores the unit tests via github actions.
> TASK: Use github actions instead of TravisCi

- Classes/Runtime/FusionObjects/AbstractCollectionFusionObject.php
The arrayCollection detected untyped properties by checking that no reserved fusion path was set.
This caused otherwise untyped properties that had @if or @process to not be interpreted with the selected
itemPrototype.
> BUGFIX: Render collection items with implicit nodetype that have meta attributes correctly

- Classes/Domain/Field.php
When validation errors are present the field value only tries to access the submitted values.
This caused confusion when bound data had a value for the path but the submitted values did not.
The change adds a fallback from submitted values to bound data in case the submitted data is null.
Resolves: #48
> BUGFIX: Render bound data when submitted values are null

- Resources/Private/Fusion/Prototypes/ErrorRenderer.fusion
```
prototype(Test.Test:Content.ContactForm) < prototype(Neos.Neos:ContentComponent) {
renderer = Neos.Fusion.Form:Runtime.RuntimeForm {
process = Neos.Fusion.Form:Runtime.SingleStepProcess {
schema {
name = ${Form.Schema.string().isRequired().validator('StringLength', {minimum: 3, maximum: 100})}
}
content = afx`
<Neos.Fusion.Form:FieldContainer field.name="name" label="NAME">
<Neos.Fusion.Form:Input errorClass="is-invalid" attributes.class="form-control" attributes.id="name" attributes.required="required"/>
</Neos.Fusion.Form:FieldContainer>
`
}
}
}
```
When validation fails, arguments are not applied to translation message:
`Die Länge des Textes muss zwischen {0,number} und {1,number} Zeichen liegen`
`Die Länge des Textes muss zwischen 3 und 100 Zeichen liegen`
> BUGFIX: validation error rendering

- composer.json
I'm currently investigating failing E2E tests in the Neos UI repository. While I could fix the problem for the `master` branch, there's still trouble remaining for `7.0`.
In PR https://github.com/neos/neos-ui/pull/2922 I found out, that the problem is due to a deprecated Guzzle function used here:
https://github.com/neos/flow-development-collection/blob/7.0/Neos.Flow/Classes/Mvc/ActionResponse.php#L6
And a broken version Constraint in Neos.Http.Factories 7.0.7:
https://github.com/neos/flow-development-collection/blob/7.0.7/Neos.Http.Factories/composer.json#L12
Which is actually fixed in 7.0.8:
https://github.com/neos/flow-development-collection/blob/7.0.8/Neos.Http.Factories/composer.json#L12
Nevertheless, composer consistently installs Neos.Http.Factories 7.0.7 instead of 7.0.8. 
This is …
> BUGFIX: Relax version constraint for guzzlehttp/psr7

- Classes/Runtime/Action/RedirectAction.php
- composer.json
This allows to remove the explicit dependency to guzzle which caused trouble in the past.
> TASK: Use psr/http-factoris to create redirect uri

- Resources/Private/Fusion/Prototypes/FieldContainer.fusion
Without braces the props.class is ignored and props.error is always rendered.
> BUGFIX: props.class ignored in FieldContainer

- Classes/Runtime/FusionObjects/MultiStepProcessImplementation.php
Currently the `data` is only pushed to the context before the subprocess is rendered. This change ensures
that the `data` is pushed in the context immediately after it is restored from the form state and stays there for the remaining part of the `handle` method. This ensures it is available while the subprocesses are evaluated the handling of the request is delegated to the submitted step.
That way schemas may use the data for instance to configure fields as required if other fields are set.
```
process = Neos.Fusion.Form:Runtime.MultiStepProcess {
steps {
second {
...
schema {
conditionalField = ${Form.Schema.string()}
conditionalField.@process.makeRequired = ${value.isRequired()}
conditionalField.@process.makeRequired.@if.hasOtherValue = ${data.otherValue}
}
}
}
}
```
This even allows …
> BUGFIX: Make previous data available to the fusion contexts before subprocesses are evaluated.

- Documentation/FormBasics.md
Hey 👋 
I just stumbled upon a 404 link in the docs
> DOCS: fix link to fusion reference

- Documentation/FusionReference.rst
The Date input is missing in the fusion reference
> DOCS: add Neos.Fusion.Form:Date to docs

- Classes/Domain/Form.php
- Tests/Functional/FormTest.php
If the target the form is submitted to has query arguments those will not be submitted. This change adds those to the hidden fields. This is helpful and mimics a similar behavior of the fluid forms.
See: https://github.com/neos/flow-development-collection/blob/master/Neos.FluidAdaptor/Classes/ViewHelpers/FormViewHelper.php#L252-L268
> FEATURE: Add query arguments from form target uri to hidden fields if method == `get`

- Documentation/Examples/FrontendForm.md
I tried to create my first form based on this package and received an error message after copying the example
> Add missing quotes in example

- Classes/Domain/AbstractFormObject.php
- Classes/Domain/Field.php
- Classes/Domain/Option.php
- Classes/FusionObjects/FieldDefinitionImplementation.php
- Classes/FusionObjects/FormDefinitionImplementation.php
- Classes/Runtime/Action/EmailAction.php
- Classes/Runtime/Domain/ActionResolver.php
- Classes/Runtime/FusionObjects/ActionImplementation.php
- Classes/Runtime/FusionObjects/RuntimeFormImplementation.php
- Classes/Runtime/Helper/SchemaDefinition.php
With Neos 9.0 it will not be possible to replace fusion globals like `request` via `pushContext` instead the internal `pushContextArray` has to be used for that. See https://github.com/neos/neos-development-collection/pull/4425
This change adjusts the code to always use `pushContextArray` to set the form subrequest which works in all supported versions of Neos.
> Bugfix: Adjust to api changes in Neos 9.0

- Documentation/FusionReference.rst
- Resources/Private/Fusion/Prototypes/Upload.fusion
The new option allows to specify a collection other than `persistent` where the uploaded file will be stored. This is analog to a feature of the UploadViewHelper that until now had no equivalent in fusion form.
> FEATURE: Add `collectionName` option to `Neos.Fusion.Form:Upload`

- Classes/Domain/Form.php
- Classes/FusionObjects/FormDefinitionImplementation.php
- Classes/Runtime/FusionObjects/RuntimeFormImplementation.php
- Documentation/FusionReference.rst
- Resources/Private/Fusion/Prototypes/Definition/Form.fusion
- Tests/Functional/FormTest.php
FEATURE: Add `enableReferrer ` and `enableTrustedProperties` to the prototype `Neos.Fusion.Form:Definition.Form` 
Both settings are disabled by default which does not change the current behavior.
- `enableReferrer`: (bool, defaults to true) Enable the generation of hidden `__referrer` fields. Can be disabled when the `method` is `get` or no flow validation is used
- `enableTrustedProperties`: (bool, defaults to true) Enable the generation of hidden `__trustedProperties` fields. Can be disabled when flow property mapping is not in use
In Addition the RuntimeForm now sets `enableReferrer` to `false` because the runtime form only uses trusted properties but will never redirect back to the referrer.
Resolves: #73
> FEATURE: Add `enableReferrer` and `enableTrustedProperties` to the Form Definition

- Classes/Domain/AbstractFormObject.php
I use field[0] and field[1] in a Fusion Form in conjunction with a validator. Without this condition, I end up in
`Warning: Array to string conversion in /data/neos/Packages/Application/Neos.Fusion.Form/Classes/Domain/AbstractFormObject.php line 42`
> added an additional condition for arrays

- Classes/Domain/AbstractFormObject.php
- Classes/Domain/Field.php
- Classes/Domain/Form.php
- Classes/Runtime/Helper/ArrayOfSchemaDefinition.php
...by removing implicit nullability
Note: This package declares compatibility with PHP 7.2, nullable parameters are supported from 7.1 on and are thus safe.
> Fix PHP 8.4 deprecation warnings

- .github/workflows/build.yml
- Classes/Domain/Form.php
- Classes/Runtime/Action/EmailAction.php
- Classes/Runtime/FusionObjects/ValidatorImplementation.php
- Classes/Runtime/Helper/SchemaDefinition.php
- Documentation/RuntimeActionReference.rst
- composer.json
- phpstan.neon
Removes the outdated swiftmailer and uses the new symfonymailer package for the email action.
> !!! FEATURE: Replace swiftmailer with symfonymailer

- Classes/Runtime/Action/EmailAction.php
This is not needed anymore, as the neos/symfonymailer package is now a dependency and always installed.
See #95
> TASK: Remove check if symfonymailer package is installed

- Classes/Runtime/Action/EmailAction.php
- composer.json
To prevent a hard dependency to the neos/symfonymailer package, the MailerService is fetched directly from the object manager. The ProxyBuilding doesn't allow any injection without the class existing.
> TASK: Make neos/symfonymailer an optional dependency
